### PR TITLE
V5 dev: Implement v5 API

### PR DESCRIPTION
**Pull request by jsTron**
* Update requests, events, and types to reflect the v5 API of obs-websocket.
* Update test client to an almost complete state for new API.
  - Some features are disabled and need refactoring.
* Update version in readme to v5.0.0

### CODE REVIEW

**Comment by ImBada** [comment]
Hi, There's a typo:

PressInputPropertiesbutton -> PressInputPropertiesButton

**Comment by ImBada** [comment]
In `HandleAuthentication` function, we should remove this line:
`connectionPassword = null;`
Not sure why it's here, but it occurs an error when auto-reconnecting the obs-websocket v5.

**Comment by jsTron** [comment]
> 

I'm not sure why it is there either. I don't believe that method was touched in this PR. Maybe a new issue should be opened? I don't believe I have experienced the error you are reporting.

**Comment by ImBada** [comment]
ok. maybe I should open a new issues. you can experience this issue when you use the websocket longer than 3~5 mins.

**Comment by jsTron** [comment]
It may be worth noting that the absence of the heartbeat request now requires the client application to poll the service within 60 seconds to keep the connection and authentication alive. Getting the stream status regularly would satisfy this requirement.

**Comment by BarRaider** [comment]
Merge Conflicts with previous PRs

**Comment by BarRaider** [comment]
@jsTron let me know if you have capacity fixing the merge requests, if not I'll try to give it a shot. Waiting for this PR before I put in additional updates.

**Comment by jsTron** [comment]
@BarRaider I should be able to take a peek at it this evening and/or during the day tomorrow.

**Comment by jsTron** [comment]
@BarRaider The merge conflicts should be fixed and force-pushed now.

**Comment by BarRaider** [comment]
Will take a look a bit later

**Comment by jsTron** [comment]
Sounds good. It should be in a pretty good state right now.

**Pull request merged**
