### PR TITLE
Fix GitHub Actions

### PR DESCRIPTION
**Pull request by IlyaBat9**
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

### CODE REVIEW

**Review by pkup1618 — APPROVED** [review]

**Comment by toplenboren** [comment]
+ really need that PR

**Comment by BarRaider** [comment]
Hi, thanks for taking the initiative!
As it's big, will review ASAP and comment/approve as needed.

**Comment by BarRaider** [comment]
Can you please move the PR into the dev-4.9 so I can approve?
There is already some code there that conflicts with this one so it'll prevent a even more complicated merge back to master

**Comment by tinodo** [comment]
I added some more changes in a Pull request against the master branch. I could not use the dev-4.9 branch. (It wouldn't compile). So I added my final changes to the master branch to complete the implementation of obs websocket 4.9.0. (To the same Pull request.)

**Pull request merged**
