### PR TITLE
Allow to `await` ConnectAsync()

### PR DESCRIPTION
**Pull request by DmitriySalnikov**
This PR does not change the behavior of this function in the already existing code.
But it allows you to wait for the connection attempt to complete.

### CODE REVIEW

**Comment by BarRaider** [comment]
I don't think this is a good update as it will confuse people to think that after an await they can immediately call the websocket methods, instead of listening to the connect event

**Comment by DmitriySalnikov** [comment]
Yes, I forgot that there is still a need for authorization. But one more NOTE can be added or `<returns></returns>`.

At the moment I'm using `await ConnectAsync()` to do auto-reconnection in an infinite loop. How to do it simply, without errors and without `await` I don't know.

**Comment by DmitriySalnikov** [comment]
Added a clarification.

**Comment by BarRaider** [comment]
Sorry, I still don't understand why I would want to push this. It's confusing.
What's your use-case for putting this in await?

**Comment by DmitriySalnikov** [comment]
> What's your use-case for putting this in await?

I have already written this

> At the moment I'm using `await ConnectAsync()` to do auto-reconnection in an infinite loop. How to do it simply, without errors and without `await` I don't know.

Simplified version of my code:

```cs
async void ReconnectionThread()
{
    while (true)
    {
        try
        {
            await obs.ConnectAsync("ws://localhost:4455", "pass");
        }
        catch {}

        if (obs.IsConnected || reconnectCancellationToken.IsCancellationRequested) return;

        Thread.Sleep(4000);
    }
}
```

It's just a Task that runs when disconnected from OBS.

It is as simple and convenient as possible. If you do the same without await, you may have problems trying to connect during another connection attempt or reconnecting when the connection is already established.

**Comment by BarRaider** [comment]
Your code would work EXACTLY the same without that await, given there is nothing blocking in the ConnectAsync function.
Overall, the right way to do this is to listen to the Connect and Disconnect events and use them to decide when to call ConnectAsync again.

**Comment by DmitriySalnikov** [comment]
@BarRaider Will #100 be ignored?

**Pull request closed without merging**
